### ISSUE TITLE
navbar的字长了会排版错乱问题

### ISSUE THREAD

**Issue by brianway** [Gaohaoyang/gaohaoyang.github.io#4]
你好，首先感谢你的模板。

navbar每一项的长度有限制，长了会排版错乱。
比如，将"pages/about.md"的title改成“my projects”,排版乱了。
我试了搜狗和chrome浏览器，都是的。

我把"static/css/index.css":`width: 95px;`改成下面的形式，解决了。

```css
.navbar-nav li{
	min-width: 95px;
	text-align: center;
}
```
我不懂前端，完全是是对照[LiXizhi](https://github.com/LiXizhi)的主页代码和你的找出来的解决。
另外，这个人的代码组织在你基础上有改进，比如duoshuo的评论是用site的配置项，而不是写死在网页里，更方便使用者改动

**详情**可以参看我的[README](https://github.com/brianway/brianway.github.io)

附上我的主页[brianway](http://brianway.github.io/),再次感谢，已star+following you
